import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '../components/navbar/Navbar'
import Navbar from "../components/navbar/Navbar";
import Footer from "@/components/Footer";
import NextAuthProviders from "@/Providers/NextAuthProviders";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${inter.className} antialiased`}
      >
        <NextAuthProviders>
          <Toaster />
          <Navbar />
          <main>{children}</main>
          <Footer />
        </NextAuthProviders>
      </body>
    </html>
  );
}
